In [30]:
import pandas as pd
from os import listdir
from os.path import isfile, join

reading_folder = "./data/population/"
files = [f for f in listdir(pop_path) if isfile(join(reading_folder, f))]

pdfs = []
for file in files:
    print("Reading {} ...".format(file))
    pdfs.append(pd.read_csv(reading_folder + file))
    
# Merge into one huge data matrix
pd_all = pd.concat(pdfs).reset_index(drop=True)
print(pd_all.shape)

Reading IHME_GBD_2017_POP_1990_1994_Y2018M11D08.CSV ...
Reading IHME_GBD_2017_POP_1995_1999_Y2018M11D08.CSV ...
Reading IHME_GBD_2017_POP_2000_2004_Y2018M11D08.CSV ...
Reading IHME_GBD_2017_POP_2005_2009_Y2018M11D08.CSV ...
Reading IHME_GBD_2017_POP_2010_2014_Y2018M11D08.CSV ...
Reading IHME_GBD_2017_POP_2015_2017_Y2018M11D08.CSV ...
(5239668, 13)

In [31]:
glob = ['Global']
continents = ['Asia', 'Europe', 'Oceania', 'America', 'Africa']
countries = [ i for i in sorted(pd_all.location_name.unique()) if ((not i in continents) and (i != 'Global'))]

### SET THE LOCATION YOU WANT HERE ###
locations = continents
locations_name = "continents"

In [32]:
# drop id columns
to_drop = [col for col in pd_all.columns if "id" in col and 'year' not in col]
print(to_drop)

pd_all = pd_all.drop(columns = to_drop, axis=1)

['location_id', 'sex_id', 'age_group_id', 'measure_id']

In [33]:
pd_loc = pd_all[pd_all.location_name.isin(locations)]
pd_loc

,location_name,sex_name,age_group_name,year_id,measure_name,metric_name,val,upper,lower
25935,Africa,Male,Under 5,1990,Population,Number,5.563377e+07,5.672142e+07,5.442964e+07
25936,Africa,Male,Under 5,1991,Population,Number,5.670544e+07,5.784434e+07,5.553707e+07
25937,Africa,Male,Under 5,1992,Population,Number,5.775862e+07,5.894548e+07,5.650543e+07
25938,Africa,Male,Under 5,1993,Population,Number,5.871194e+07,5.988070e+07,5.744522e+07
25939,Africa,Male,Under 5,1994,Population,Number,5.977465e+07,6.099619e+07,5.841769e+07
25940,Africa,Male,Early Neonatal,1990,Population,Number,2.580701e+05,2.632036e+05,2.524276e+05
25941,Africa,Male,Early Neonatal,1991,Population,Number,2.626823e+05,2.679384e+05,2.571789e+05
25942,Africa,Male,Early Neonatal,1992,Population,Number,2.673202e+05,2.727677e+05,2.614082e+05
25943,Africa,Male,Early Neonatal,1993,Population,Number,2.710715e+05,2.767665e+05,2.649636e+05
25944,Africa,Male,Early Neonatal,1994,Population,Number,2.750592e+05,2.808935e+05,2.686789e+05
25945,Africa,Male,Late Neonatal,1990,Population,Number,7.548716e+05,7.699088e+05,7.384089e+05
25946,Africa,Male,Late Neonatal,1991,Population,Number,7.686016e+05,7.840242e+05,7.525397e+05
25947,Africa,Male,Late Neonatal,1992,Population,Number,7.822844e+05,7.981986e+05,7.649561e+05
25948,Africa,Male,Late Neonatal,1993,Population,Number,7.934008e+05,8.099691e+05,7.755607e+05
25949,Africa,Male,Late Neonatal,1994,Population,Number,8.053856e+05,8.223534e+05,7.867047e+05
25950,Africa,Male,Post Neonatal,1990,Population,Number,1.154300e+07,1.177252e+07,1.129310e+07
25951,Africa,Male,Post Neonatal,1991,Population,Number,1.176312e+07,1.199998e+07,1.151931e+07
25952,Africa,Male,Post Neonatal,1992,Population,Number,1.196850e+07,1.221076e+07,1.170371e+07
25953,Africa,Male,Post Neonatal,1993,Population,Number,1.214249e+07,1.239230e+07,1.187160e+07
25954,Africa,Male,Post Neonatal,1994,Population,Number,1.236443e+07,1.262249e+07,1.207905e+07
25955,Africa,Male,1 to 4,1990,Population,Number,4.307783e+07,4.393123e+07,4.214975e+07
25956,Africa,Male,1 to 4,1991,Population,Number,4.391103e+07,4.478746e+07,4.300300e+07
25957,Africa,Male,1 to 4,1992,Population,Number,4.474052e+07,4.565553e+07,4.377143e+07
25958,Africa,Male,1 to 4,1993,Population,Number,4.550498e+07,4.641066e+07,4.452726e+07
25959,Africa,Male,1 to 4,1994,Population,Number,4.632978e+07,4.727414e+07,4.528388e+07
25960,Africa,Male,5 to 9,1990,Population,Number,4.605740e+07,4.697156e+07,4.507546e+07
25961,Africa,Male,5 to 9,1991,Population,Number,4.712566e+07,4.807035e+07,4.613637e+07
25962,Africa,Male,5 to 9,1992,Population,Number,4.822062e+07,4.919813e+07,4.720368e+07
25963,Africa,Male,5 to 9,1993,Population,Number,4.921090e+07,5.018730e+07,4.817143e+07
25964,Africa,Male,5 to 9,1994,Population,Number,5.022781e+07,5.124927e+07,4.913384e+07
...,...,...,...,...,...,...,...,...,...
5106771,Oceania,Both,92,2015,Population,Number,4.201508e+02,4.375131e+02,4.021266e+02
5106772,Oceania,Both,92,2016,Population,Number,4.367796e+02,4.566761e+02,4.170225e+02
5106773,Oceania,Both,92,2017,Population,Number,4.525207e+02,4.742062e+02,4.303294e+02
5106774,Oceania,Both,93,2015,Population,Number,2.958504e+02,3.076945e+02,2.835632e+02
5106775,Oceania,Both,93,2016,Population,Number,3.085894e+02,3.222205e+02,2.951247e+02
5106776,Oceania,Both,93,2017,Population,Number,3.205010e+02,3.352230e+02,3.049714e+02
5106777,Oceania,Both,94,2015,Population,Number,2.049888e+02,2.130553e+02,1.966171e+02
5106778,Oceania,Both,94,2016,Population,Number,2.128001e+02,2.218091e+02,2.037552e+02
5106779,Oceania,Both,94,2017,Population,Number,2.216533e+02,2.315249e+02,2.112316e+02
5106780,Oceania,Both,25 plus,2015,Population,Number,5.255003e+06,5.611022e+06,4.907753e+06
5106781,Oceania,Both,25 plus,2016,Population,Number,5.406406e+06,5.821226e+06,5.017641e+06
5106782,Oceania,Both,25 plus,2017,Population,Number,5.561298e+06,6.014350e+06,5.124899e+06
5106783,Oceania,Both,<20 years,2015,Population,Number,5.653091e+06,6.058723e+06,5.258812e+06
5106784,Oceania,Both,<20 years,2016,Population,Number,5.757971e+06,6.224071e+06,5.327590e+06
5106785,Oceania,Both,<20 years,2017,Population,Number,5.864616e+06,6.364012e+06,5.377130e+06
5106786,Oceania,Both,10 to 24,2015,Population,Number,3.647229e+06,3.907106e+06,3.394973e+06
5106787,Oceania,Both,10 to 24,2016,Population,Number,3.705038e+06,4.003023e+06,3.431043e+06
5106788,Oceania,Both,10 to 24,2017,Population,Number,3.765074e+06,4.083914e+06,3.454222e+06
5106789,Oceania,Both,10 to 19,2015,Population,Number,2.522034e+06,2.701398e+06,2.347970e+06
5106790,Oceania,Both,10 to 19,2016,Population,Number,2.553484e+06,2.758243e+06,2.365274e+06
5106791,Oceania,Both,10 to 19,2017,Population,Number,2.588261e+06,2.806811e+06,2.375365e+06
5106792,Oceania,Both,Birth,2015,Population,Number,3.861337e+05,4.192987e+05,3.542246e+05
5106793,Oceania,Both,Birth,2016,Population,Number,3.912897e+05,4.251190e+05,3.588404e+05
5106794,Oceania,Both,Birth,2017,Population,Number,3.986113e+05,4.337640e+05,3.647184e+05
5106795,Oceania,Both,95 plus,2015,Population,Number,3.769497e+02,3.909229e+02,3.622834e+02
5106796,Oceania,Both,95 plus,2015,Population,Number,3.769497e+02,3.909229e+02,3.622834e+02
5106797,Oceania,Both,95 plus,2016,Population,Number,3.928344e+02,4.083918e+02,3.765426e+02
5106798,Oceania,Both,95 plus,2016,Population,Number,3.928344e+02,4.083918e+02,3.765426e+02
5106799,Oceania,Both,95 plus,2017,Population,Number,4.080852e+02,4.253776e+02,3.898661e+02
5106800,Oceania,Both,95 plus,2017,Population,Number,4.080852e+02,4.253776e+02,3.898661e+02

In [34]:
pd_loc.to_csv('population_{}_1990_2017.csv'.format(locations_name))